# Generated by Django 5.2.1 on 2025-05-29 14:33

import django.db.models.deletion
import scanner.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("service_name", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "completed"),
                            ("failed", "failed"),
                            ("in_progress", "in_progress"),
                            ("pending", "pending"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("aws", "aws"),
                            ("azure", "azure"),
                            ("gcp", "gcp"),
                            ("kubernetes", "kubernetes"),
                            ("m365", "m365"),
                            ("nhn", "nhn"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severities",
                    scanner.fields.MultiSelectField(
                        choices=[
                            ("critical", "critical"),
                            ("high", "high"),
                            ("informational", "informational"),
                            ("low", "low"),
                            ("medium", "medium"),
                        ],
                        max_length=200,
                    ),
                ),
                ("start", models.DateTimeField(null=True)),
                ("end", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("title", models.TextField()),
                ("resource_name", models.CharField(max_length=255)),
                ("resource_type", models.CharField(max_length=255)),
                ("risk", models.TextField()),
                ("remediation", models.TextField()),
                (
                    "scan_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="scanner.check",
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
            },
        ),
        migrations.AddField(
            model_name="check",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="scanner.scan",
            ),
        ),
    ]
